#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Dec 06, 2017 06:25:00 AM

#======================================================
#    SecondApp_support.py
#------------------------------------------------------
# Created for the Page Tutorial Project
# Written by G.D. Walters
# Copyright (c) 2018 by G.D. Walters
# This source code is released under the MIT License 
# (See MIT_License.txt)
#======================================================

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global Colors
    Colors = StringVar()
    global che39
    che39 = StringVar()
    global che40
    che40 = StringVar()
    global che41
    che41 = StringVar()

def btnExit_lclick(p1):
    print('SecondApp_support.btnExit_lclick')
    sys.stdout.flush()
    destroy_window()
    
def btnGetChecks_lclick(p1):
    print('SecondApp_support.btnGetChecks_lclick')
    sys.stdout.flush()
    if che39.get() == "1":
        print("chkApples")
    if che40.get() == "1":
        print("chkBanana")
    if che41.get() == "1":
        print("chkGrapes")
    
def btnGetText_lclick(p1):
    print('SecondApp_support.btnGetText_lclick')
    sys.stdout.flush()
    print(w.entryExample.get())
    
def ClearChecks():
    che41.set("0")
    che40.set("0")
    che39.set("0")
    
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    Colors.set("Blue")
    ClearChecks()
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SecondApp
    SecondApp.vp_start_gui()


